Add javadoc plugin; 0.0.6-SNAPSHOT->0.0.7-SNAPSHOT
wildfly-extras/wildfly-grpc-feature-pack pull request #80
Opened 2023-03-28 18:49 UTC by ronsigal

When I wanted a RESTEasy gRPC test to run in a pull request, I needed a wildfly-grpc-feature-pack available from a repository. There were three issues:

1. the main pom.xml refers to 

        <repository>
            <id>ossrh</id>
            <url>${repo.sonatype.url}/service/local/staging/deploy/maven2/</url>
        </repository>

and I don't have an account there, so I commented it out and deployed to https://repository.jboss.org/nexus

2. https://repository.jboss.org/nexus doesn't like a staging repo with a SNAPSHOT version, so, temporarily, I changed the version to 0.0.6.

3. Deploying to https://repository.jboss.org/nexus, wildfly.grpc.api and wildfly.grpc.subsystem failed because there was no javadoc jar, so in this pull request I've  added that.

2023-03-29 06:33 UTC, hpehl commented
I think we should stick with deploying to Maven Central.  

Looking at Maven Central, I see there are already several versions deployed: https://central.sonatype.com/namespace/org.wildfly.extras.grpc

I remember I released version [0.0.3.Final](https://central.sonatype.com/artifact/org.wildfly.extras.grpc/wildfly-grpc-parent/0.0.3.Final) some time ago using the [`./release.sh`](https://github.com/wildfly-extras/wildfly-grpc-feature-pack/blob/main/release.sh) script. 

There are also versions `0.0.5` and `0.0.6` on Maven Central, released three days ago. Though I don't know where they come from. I cannot find a related [release entry](https://github.com/wildfly-extras/wildfly-grpc-feature-pack/releases) or tag on GitHub.

Please let me know if there are issues with releasing on Maven Central. I wrote an [article](https://gist.github.com/hpehl/dc0bc0a3300fd50ed874c56777ef95c1) some time ago about releasing on Maven Central. The [`./release.sh`](https://github.com/wildfly-extras/wildfly-grpc-feature-pack/blob/main/release.sh) script and the related [`release.yml`](https://github.com/wildfly-extras/wildfly-grpc-feature-pack/blob/main/.github/workflows/release.yml) workflow should make it possible to release new versions easily.

2023-03-29 15:44 UTC, ronsigal commented
Hey @hpehl,

The POM points to ${repo.sonatype.url}, defined as https://oss.sonatype.org. Is that Maven Central? 

I needed an accessible version of wildfly-grpc-feature-pack for a test in a pull request to work, so I tried to deploy to https://oss.sonatype.org, but, without an account, it rejected me. So I deployed to https://repository.jboss.org, where I have the right permissions. That's where 0.0.5 and 0.0.6 come from. I guess they get pushed to Maven Central from there?

I didn't notice release.sh. Maybe that would have worked for me ...

-Ron

2023-03-29 16:52 UTC, jamezp commented
+1 on continuing to deploy to Maven Central.

2023-04-12 10:09 UTC, hpehl commented
@ronsigal has this PR been superseded by #81

2023-04-12 10:39 UTC, hpehl requested changes
@ronsigal I'm not 100% sure, but I think we can close this PR now that #81 has been merged.

2023-04-12 18:55 UTC, ronsigal commented
Yeah, I'll close this.

2023-04-12 18:55 UTC, closed without merging